twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        recaptcha_site_key: '%env(RECAPTCHA_SITE_KEY)%'

when@test:
    twig:
        strict_variables: true
